[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
amm = "C1omr5EZqAf72xsVEzUsF1F8yaqwpGfu2iuFwKALcBgB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
