[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault_anchor = "6NPUTr5MM4ViKqDC4MzX1epkYD8PZ32RGNkTbjpKFcaY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
